### ISSUE TITLE
duplex() won't run

### ISSUE THREAD

**Issue by faurehu** [Raynos/duplexer#11]
In the npm website your example says to call duplexer you can use duplex(writeStream,readStream) but that didn't work for me until I used duplexer(writeStream,readStream).

**Comment by dominictarr** [comment]
I don't understand what you did different? just the name? that is just what you import it to
`var duplexer = require('duplexer'); duplexer(ws, rs)`

**Comment by faurehu** [comment]
Ah ok, I get it now.
